#!/bin/bash

echo "=========================================="
echo "  My Portfolio - Setup Instructions"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: Node.js v20+ Required"
echo ""
echo "Current Node version: $(node --version)"
echo ""
echo "If your Node version is below v20.9.0, please update:"
echo ""
echo "Option 1 - Using NVM (Recommended):"
echo "  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
echo "  source ~/.bashrc"
echo "  nvm install 20"
echo "  nvm use 20"
echo ""
echo "Option 2 - Using apt (Ubuntu/Debian):"
echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
echo "  sudo apt-get install -y nodejs"
echo ""
echo "=========================================="
echo "  After updating Node.js, run:"
echo "=========================================="
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Start development server:"
echo "   npm run dev"
echo ""
echo "3. Open browser:"
echo "   http://localhost:3000"
echo ""
echo "=========================================="
echo "  Project Structure Created ✓"
echo "=========================================="
echo ""
echo "✓ Next.js 14 with App Router"
echo "✓ TypeScript configuration"
echo "✓ Tailwind CSS setup"
echo "✓ Component files (NeuralNetwork, HUD)"
echo "✓ Project data and routing"
echo "✓ Case study pages"
echo ""
echo "Next steps:"
echo "1. Update Node.js to v20+"
echo "2. Run 'npm install' in the my-portfolio directory"
echo "3. Customize your portfolio in src/lib/projects.ts"
echo "4. Update your name in src/components/NeuralNetwork.tsx"
echo ""
echo "Happy coding! 🚀"
